# Generated by Django 4.1 on 2025-11-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Gênero',
                'verbose_name_plural': 'Tipos de Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Gênero')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Gênero')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogacao.tipo', verbose_name='Tipo Associado')),
            ],
            options={
                'verbose_name': 'Gênero Textual',
                'verbose_name_plural': 'Gêneros Textuais',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Completo do Texto')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogacao.genero', verbose_name='Gênero Textual')),
            ],
            options={
                'verbose_name': 'Documento Catalogado',
                'verbose_name_plural': 'Documentos Catalogados',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
